### ISSUE TITLE
Primitive long is working just fine with native DTOs

### ISSUE THREAD

**Issue by slavap** [intendia-oss/autorest#12]
https://github.com/intendia-oss/autorest/wiki/JsInterop-DTO-strategy

Doesn't mention long as supported type, but it works just fine, though perhaps limited to 44bits.

**Comment by ibaca** [comment]
You are right, and it was introduced in GWT 2.8.0-beta1 almost 4 years ago. I'll update with this suggestion. 👍

https://github.com/gwtproject/gwt/commit/e31f9a4afaf5392d57c84d049230966b5918dbf8

**Comment by ibaca** [comment]
I have updated the document, this is a bit dangerous, and I thought it will show a warning during compilation, but I just tested and GWT does not print any warning. For `date`, this solution might be better than using an `int`.
