### ISSUE TITLE
autorest and jersey

### ISSUE THREAD

**Issue by mamta** [intendia-oss/autorest#13]
Hi, 

https://github.com/mamta/autorestjerseyplayground

In my project I am using autorest and jersey. I can get json from server, it works fine. 

I created UserInfo in shared module which I want to send to the client, but didn't succeed. 
Just want to confirm if the idea is correct. 

The calls which are not working -

http://localhost:8080/rest/UserInfoService/userinfo/singleuser

http://localhost:8080/rest/AppService/start/info

Thanks and regards.

**Comment by ibaca** [comment]
Change `UserInfoSerivce`, and return `Single<UserInfo>` instead of `Observable<UserInfo>`.

**Comment by mamta** [comment]
Thanks, it helped. I committed the change which you have suggested.
