### ISSUE TITLE
Eclipse gets confused about the processor generated Java files

### ISSUE THREAD

**Issue by jesperldk** [intendia-oss/autorest#4]
I have a problem with the processor, that probably is Eclipse related.
I have a resource with @AutoRestGwt, and the processor generates a _RestServiceModel just fine. When I use this Class, then Eclipse compiles this reference fine as well.
When I do an Eclipse clean or a Maven clean, the generated class gets deleted and then created again as it should. But now Eclipse can not see the class and references to the class gives Eclipse compile errors!?!
My only work-around is to rename the resource to something else and then rename it back again - then Eclipse can see it again and compile references without errors.
I have my own processor that runs on some API classes at pretty much the same time, and classes generated with this processor does not have that problem. So, I am pretty sure it has something to do with how the AutoRest processer works.

**Comment by ibaca** [comment]
Uoo... I don't use eclipse anymore, this is a weird error so if you help a bit more to detect the problem will be awesome. The processor is pretty simple, and if you have created your own processor you might try to see if I do something different. I really don't know where to start finding the problem...

**Comment by ibaca** [comment]
maybe it generate de .java or .class in a different output folder or some weird situation, you may try to repeat the bug, and find in your folder to see the .class and .java in all your folders, something like `find . -name "*_RestServiceModel.*"`, and compare the result with the java files created by your processor.

**Comment by jesperldk** [comment]
Year, I just hoped you used Eclipse now and then ;-) Debugging a processor in Eclipse is a bitch :-(
Your processor is generating .java and it gets compiled into .class - Eclipse just refuses to see it. Might well be some Eclipse bug. I would guess that the processor gets run'ed a bit differently after a clean than after a source change.
My only theory is that the problem is your
         if (roundEnv.processingOver()) return false;
I will try to do it differently, but it will have to wait for a week or two.

**Comment by jesperldk** [comment]
Okay, did some googling. There are known problems with Eclipse in this area, so I will close this issue.
My own processor works, so I hope I can make the AutoRest processor work as well by changing the flow in the processor a bit, but it will have to wait until later.

**Comment by ibaca** [comment]
To debug processor my trick is to debug the compile maven goal, it works in any IDE. Probably you need to debug clean compile so the processor get executed always.
