### ISSUE TITLE
a new annotation has been introduced (rx.internal.util.GwtIncompatible)

### ISSUE THREAD

**Issue by jschoedt** [intendia-oss/autorest#7]
Trying to get this to work with Errai 4.1.0 but when adding autorest 0.7 I get this. Any clue?

Thanks

`
[WARNING] java.lang.RuntimeException: a new annotation has been introduced (rx.internal.util.GwtIncompatible); you cannot currently introduce new annotations in devmode. Please restart.
[WARNING] 	at org.jboss.errai.config.rebind.MetaClassBridgeUtil.populateMetaClassFactoryFromTypeOracle(MetaClassBridgeUtil.java:88)
[WARNING] 	at org.jboss.errai.config.rebind.AbstractAsyncGenerator$2.run(AbstractAsyncGenerator.java:197)
[WARNING] 	at org.jboss.errai.config.rebind.AsyncGenerationJob.notifyStarting(AsyncGenerationJob.java:86)
[WARNING] 	at org.jboss.errai.config.rebind.AsyncGenerators.notifyStarting(AsyncGenerators.java:188)
[WARNING] 	at org.jboss.errai.config.rebind.AsyncGenerators.startAll(AsyncGenerators.java:144)
[WARNING] 	at org.jboss.errai.config.rebind.AsyncGenerators.getFutureFor(AsyncGenerators.java:55)
[WARNING] 	at org.jboss.errai.config.rebind.AsyncGenerationJob.submit(AsyncGenerationJob.java:109)
[WARNING] 	at org.jboss.errai.config.rebind.AbstractAsyncGenerator.startAsyncGeneratorsAndWaitFor(AbstractAsyncGenerator.java:203)
[WARNING] 	at org.jboss.errai.ioc.rebind.ioc.bootstrapper.IOCGenerator.generate(IOCGenerator.java:62)
...`

**Comment by ibaca** [comment]
😨 yep, this is a `rxjava-gwt` bug. It only includes this GwtIncompatible as a super-source and looks like this is not a good idea. I'll release rxjava-gwt 1.3.4 during this week with this problem fixed. In the mean time you can just create the annotation in your project (ie. in your src/main/java folder). The file should look like:
```java
package rx.internal.util;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@Retention(RetentionPolicy.CLASS) @Documented
@Target({ ElementType.TYPE, ElementType.METHOD, ElementType.CONSTRUCTOR, ElementType.FIELD })
public @interface GwtIncompatible {
    String value() default "";
}
```

**Comment by jschoedt** [comment]
Thanks, and what you suggest works.

**Comment by ibaca** [comment]
I have just released `rxjava-gwt:1.3.4-gwt1` and verified that it fixes the errai generator problem. You need to add an explicit dependency to `rxjava:1.3.4` and `rxjava-gwt:1.3.4-gwt1`. 👍

**Comment by ibaca** [comment]
By the way, you can use rxjava2, AutoREST it is mainly a REST metadata extractor so you can create your own request easily, this means, creating your own RequestResourceBuilder is recommended and fun 😜. And so for example, you can start just copying the provided one and migrating to RxJava 2, hehe just fun! In a small project, it looks overkilling, but you pretty soon will see how easy and powerful it is. If you have doubts you can ask in gitter 👍.

**Comment by jschoedt** [comment]
Thanks, I would like to use rxjava2 but I think that requires a bit more examples on how to do that. I have not used AutoREST before so I had to go with the examples here in the README.  
Very nice workflow with the autorest-openapi and a yaml/json spec 👍

The update works. I had to exclude rxjava-gwt from autorest-gwt:
`
<dependency>
		   <groupId>com.intendia.gwt.autorest</groupId>
		   <artifactId>autorest-gwt</artifactId>
		   <exclusions>
			   <exclusion>
				   <artifactId>rxjava-gwt</artifactId>
				   <groupId>com.intendia.gwt</groupId>
			   </exclusion>
		   </exclusions>
	   </dependency>
`
